-- SHARED CONSTANTS BETWEEN SERVER & CLIENT

BJC_EVENTS = {
    SERVER_EVENT = "BJCEvent",
    SERVER_EVENT_PARTS = "BJCEventData",
    CACHE = {
        EVENT = "BJCCache",
        TX = {
            SEND = "send",
        },
        RX = {
            REQUIRE = "require",
        },
    },
    PLAYER = {
        EVENT = "BJCPlayer",
        TX = {
            SERVER_TICK = "tick",
            TOAST = "toast",
            FLASH = "flash",
            CHAT = "chat",
            TELEPORT_TO_PLAYER = "teleportToPlayer",
            TELEPORT_TO_POS = "teleportToPos",
            EXPLODE_VEHICLE = "explodeVehicle",
            SYNC_PAINT = "syncPaint",
        },
        RX = {
            CONNECTED = "connected",
            SWITCH_VEHICLE = "switchVehicle",
            LANG = "lang",
            DRIFT = "drift",
            KM_REWARD = "KmReward",
            EXPLODE_VEHICLE = "explodeVehicle",
            MARK_INVALID_VEHS = "markInvalidVehs",
            SYNC_PAINT = "syncPaint",
            REQUEST_PAINT = "requestPaint",
        }
    },
    MODERATION = {
        EVENT = "BJCModeration",
        TX = {},
        RX = {
            MUTE = "mute",
            FREEZE = "freeze",
            ENGINE = "engine",
            KICK = "kick",
            TEMPBAN = "tempban",
            BAN = "ban",
            UNBAN = "unban",
            TELEPORT_FROM = "teleportFrom",
            SET_GROUP = "setGroup",
            DELETE_VEHICLE = "deleteVehicle",
            WHITELIST = "whitelist",
        },
    },
    CONFIG = {
        EVENT = "BJCConfig",
        TX = {},
        RX = {
            BJC = "bjc",
            ENV = "env",
            ENV_PRESET = "envPreset",
            CORE = "core",
            MAP_SWITCH = "switchMap",
            PERMISSIONS = "permissions",
            PERMISSIONS_GROUP = "permissionsGroup",
            PERMISSIONS_GROUP_SPECIFIC = "permissionsGroupSpecific",
            MAPS = "maps",
            STOP = "stop",
        },
    },
    DATABASE = {
        EVENT = "BJCDatabase",
        TX = {
            PLAYERS_GET = "playersGet",
            PLAYERS_UPDATED = "playersUpdated",
        },
        RX = {
            PLAYERS_GET = "playersGet",
            VEHICLE = "vehicle",
        },
    },
    VOTE = {
        EVENT = "BJCVote",
        TX = {},
        RX = {
            KICK_START = "KickStart",
            KICK_VOTE = "KickVote",
            KICK_STOP = "KickStop",
            MAP_START = "MapStart",
            MAP_VOTE = "MapVote",
            MAP_STOP = "MapStop",
            SCENARIO_START = "ScenarioStart",
            SCENARIO_VOTE = "ScenarioVote",
            SCENARIO_STOP = "ScenarioStop",
        },
    },
    SCENARIO = {
        EVENT = "BJCScenario",
        TX = {
            RACE_DETAILS = "RaceDetails",
            RACE_SAVE = "RaceSave",
            RACE_DELETE = "RaceDelete",
            ENERGY_STATIONS_SAVE = "EnergyStationsSave",
            GARAGES_SAVE = "GaragesSave",
            DELIVERY_SAVE = "DeliverySave",
            DELIVERY_STOP = "DeliveryStop",
            DELIVERY_PACKAGE_SUCCESS = "DeliveryPackageSuccess",
            BUS_LINES_SAVE = "BusLinesSave",
            HUNTER_INFECTED_SAVE = "HunterInfectedSave",
            DERBY_SAVE = "DerbySave",
            PURSUIT_DATA = "PursuitData",
        },
        RX = {
            RACE_DETAILS = "RaceDetails",
            RACE_SAVE = "RaceSave",
            RACE_TOGGLE = "RaceToggle",
            RACE_MULTI_UPDATE = "RaceMultiUpdate",
            RACE_MULTI_STOP = "RaceMultiStop",
            RACE_SOLO_START = "RaceSoloStart",
            RACE_SOLO_UPDATE = "RaceSoloUpdate",
            RACE_SOLO_END = "RaceSoloEnd",
            ENERGY_STATIONS_SAVE = "EnergyStationsSave",
            GARAGES_SAVE = "GaragesSave",
            DELIVERY_SAVE = "DeliverySave",
            DELIVERY_VEHICLE_START = "DeliveryVehicleStart",
            DELIVERY_VEHICLE_SUCCESS = "DeliveryVehicleSuccess",
            DELIVERY_VEHICLE_FAIL = "DeliveryVehicleFail",
            DELIVERY_PACKAGE_START = "DeliveryPackageStart",
            DELIVERY_PACKAGE_SUCCESS = "DeliveryPackageSuccess",
            DELIVERY_PACKAGE_FAIL = "DeliveryPackageFail",
            DELIVERY_MULTI_JOIN = "DeliveryMultiJoin",
            DELIVERY_MULTI_RESETTED = "DeliveryMultiResetted",
            DELIVERY_MULTI_REACHED = "DeliveryMultiReached",
            DELIVERY_MULTI_LEAVE = "DeliveryMultiLeave",
            BUS_LINES_SAVE = "BusLinesSave",
            BUS_MISSION_START = "BusMissionStart",
            BUS_MISSION_REWARD = "BusMissionReward",
            BUS_MISSION_STOP = "BusMissionStop",
            SPEED_FAIL = "SpeedFail",
            SPEED_STOP = "SpeedStop",
            HUNTER_INFECTED_SAVE = "HunterInfectedSave",
            HUNTER_UPDATE = "HunterUpdate",
            HUNTER_FORCE_FUGITIVE = "HunterForceFugitive",
            HUNTER_STOP = "HunterStop",
            INFECTED_UPDATE = "InfectedUpdate",
            INFECTED_FORCE_INFECTED = "InfectedForceInfected",
            INFECTED_STOP = "InfectedStop",
            DERBY_SAVE = "DerbySave",
            DERBY_UPDATE = "DerbyUpdate",
            DERBY_STOP = "DerbyStop",
            TAG_DUO_JOIN = "TagDuoJoin",
            TAG_DUO_UPDATE = "TagDuoUpdate",
            TAG_DUO_LEAVE = "TagDuoLeave",
            TAG_SERVER_START = "TagServerStart",
            TAG_SERVER_UPDATE = "TagServerUpdate",
            TAG_SERVER_STOP = "TagServerStop",
            PURSUIT_DATA = "PursuitData",
            PURSUIT_REWARD = "PursuitReward",
        }
    },
    TOURNAMENT = {
        EVENT = "BJCTournament",
        TX = {},
        RX = {
            CLEAR = "clear",
            TOGGLE = "toggle",
            END_TOURNAMENT = "endTournament",
            TOGGLE_WHITELIST = "toggleWhitelist",
            TOGGLE_PLAYER = "togglePlayer",
            REMOVE_ACTIVITY = "removeActivity",
            EDIT_SCORE = "editScore",
            REMOVE_PLAYER = "removePlayer",
            ADD_SOLO_RACE = "addSoloRace",
            END_SOLO_ACTIVITY = "endSoloActivity",
        },
    },
}

---@type tablelib<string, {env: string, type: string, default: any, maxLength: integer?, prevent: boolean?, min: number?, max: number?}>
BJC_CORE_CONFIG = Table({
    Debug             = { env = "BEAMMP_DEBUG", type = "boolean", default = false, },
    Private           = { env = "BEAMMP_PRIVATE", type = "boolean", default = true, },
    MaxCars           = { env = "BEAMMP_MAX_CARS", type = "number", default = 200, prevent = true, },
    MaxPlayers        = { env = "BEAMMP_MAX_PLAYERS", type = "number", default = 10, min = 1 },
    Map               = { env = "BEAMMP_MAP", type = "string", maxLength = 100, default = "/levels/gridmap_v2/info.json", },
    Name              = { env = "BEAMMP_NAME", type = "string", maxLength = 250, default = "My Awesome BeamJoy Server", },
    Description       = { env = "BEAMMP_DESCRIPTION", type = "string", maxLength = 1000, default = "This server is not configured yet but can you play with it !", },
    InformationPacket = { env = "BEAMMP_INFORMATION_PACKET", type = "boolean", default = false, },
})
BJC_CORE_CONFIG:forEach(function(el, k)
    if not el.prevent and not MP.Settings[k] then el.prevent = true end
end)

BJC_ENV_PRESETS = {
    CLEAR = "clear",
    CLOUD = "cloud",
    LIGHT_RAIN = "lightrain",
    RAIN = "rain",
    LIGHT_SNOW = "lightsnow",
    SNOW = "snow",
}
